[package]
name = "jito-protos"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
bytes = "1.4.0"
prost = "0.11.9"
prost-types = "0.11.9"
solana-perf = "1.16"
solana-sdk = "1.16"
tonic = "0.8.3"

[build-dependencies]
tonic-build = "0.8.4"
